services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
      - "578:587"
    volumes:
      - ./:/code
    command:
      sh -c "python3 manage.py makemigrations &&  python3 manage.py migrate && 
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    env_file:
      - .env.dev